#ifndef LIBPOINTCLOUDFILEMANAGER_GLOBAL_H
#define LIBPOINTCLOUDFILEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBPOINTCLOUDFILEMANAGER_LIBRARY)
#  define LIBPOINTCLOUDFILEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPOINTCLOUDFILEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPOINTCLOUDFILEMANAGER_GLOBAL_H
