#ifndef POINTCLOUDFILEDEFINITIONS_H
#define POINTCLOUDFILEDEFINITIONS_H

#define POINTCLOUDFILE_AUTHOR_EMAIL                             "david.hernandez@uclm.es"

#define POINTCLOUDFILE_WITHOUT_MAXIMUM_NUMBER_OF_POINTS_LIMITS          -1
#define POINTCLOUDFILE_MAXIMUM_NUMBER_OF_POINTS_IN_DEMO_VERSION       6000000
#define POINTCLOUDFILE_LAS_FORMAT_CLASS_GROUND                        2
#define POINTCLOUDFILE_LAS_FORMAT_CLASS_ELECTRIC_PYLON                20
#define POINTCLOUDFILE_LAS_FORMAT_CLASS_ELECTRIC_PYLONS_CONNECTION    21

//#define POINTCLOUDFILE_PROJECT_GRID_SIZE_1                            1.0
#define POINTCLOUDFILE_PROJECT_GRID_SIZE_5                            5
#define POINTCLOUDFILE_PROJECT_GRID_SIZE_10                           10
#define POINTCLOUDFILE_PROJECT_GRID_SIZE_20                           20
#define POINTCLOUDFILE_PROJECT_GRID_SIZE_50                           50
#define POINTCLOUDFILE_PROJECT_GRID_SIZE_100                           100
#define POINTCLOUDFILE_PROJECT_GRID_SIZE_200                           200
#define POINTCLOUDFILE_GRID_SIZE_FIELD_PRECISION                        1

#define POINTCLOUDFILE_PROJECT_TYPE_GENERIC_TAG                       "Generic"
#define POINTCLOUDFILE_PROJECT_TYPE_POWERLINE_TAG                     "Powerline"
#define POINTCLOUDFILE_PROJECT_TYPE_SOLARPARK_TAG                     "SolarPark"

#define POINTCLOUDFILE_PROJECT_PARAMETERS_FILE_PARAMETERS_STRING_SEPARATOR     "@p@"
#define POINTCLOUDFILE_PROJECT_PARAMETERS_FILE_PARAMETER_VALUE_STRING_SEPARATOR     "@v@"

#define POINTCLOUDFILE_PROJECT_TYPE_GENERIC_PARAMETERS_FILE_NAME     "parameters_pc_pt_generic.xml"
#define POINTCLOUDFILE_PROJECT_TYPE_POWERLINE_PARAMETERS_FILE_NAME     "parameters_pc_pt_powerline.xml"
#define POINTCLOUDFILE_PROJECT_TYPE_SOLARPARK_PARAMETERS_FILE_NAME     "parameters_pc_pt_solarpark.xml"

#define POINTCLOUDFILE_LASTOOLS_PARAMETERS_FILE_NAME                  "parameters_pc_lastools_commands.xml"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASNOISE                       "lasnoise64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASTILE                       "lastile64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING       "Powerline preprocessing"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING       "SolarPark preprocessing"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY    "Classify ground from photogrammetry"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION       "Classify buidings and high vegetation"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASCLIP                       "lasclip64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASMERGE                      "lasmerge64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASGROUND                     "lasground64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASTHIN                       "lasthin64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LAS2DEM                       "las2dem64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LAS2LAS                       "las2las64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASHEIGHT                     "lasheight64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASCLASSIFY                   "lasclassify64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASBOUNDARY                   "lasboundary64"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_PREPROCESSING       "Ellipsoid to orthometric height conversion"

#define POINTCLOUDFILE_INTERNALTOOLS_PARAMETERS_FILE_NAME                  "parameters_pc_internal_commands.xml"

#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_LAS2DEM_CLASSES       "las2dem_classes"

#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_ESTIMATE       "vegetation_growth_estimate"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_ESTIMATE_EPSG_CODE       "vge_epsg_code"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_ESTIMATE_SPATIAL_RESOLUTION       "vge_spatial_resolution"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_UPDATE_EXISTING_MODEL       "vge_update_existing_model"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_USE_MULTI_PROCESS     "vge_MultiProcess"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_MIN_YEAR       2000
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_MODEL_FILE_BASENAME   "VegetationGrowthModel"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_MODEL_FILE_EXTENSION   ".txt"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_REPORT_FILE_BASENAME   "VegetationGrowthReport"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_REPORT_FILE_EXTENSION   ".txt"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_1_STRETCH_UPPER    2
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_2_STRETCH_UPPER    5
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_3_STRETCH_UPPER    10
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_4_STRETCH_UPPER    20
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_5_STRETCH_UPPER    30
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_6_STRETCH_UPPER    40
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_STRETCH_PERCENTIL         95
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_GROWTH_MODEL_FILE_STRING_SEPARATOR    "#"
#define POINTCLOUDFILE_INTERNALTOOLS_COMMAND_VEGETATION_MINIMUM_NUMBER_OF_VALUES_FOR_STATISTICS        12



#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_GEOIDS_PATH         "/geoids_lastools"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_FILE_SUFFIX       "_msl"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_GEOIDS_FILE_SPAIN_EGM08REDNAD_25830         "EGM08_REDNAP_25830.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_GEOIDS_FILE_SPAIN_EGM08REDNAD_25829         "EGM08_REDNAP_25829.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_GEOIDS_FILE_SPAIN_EGM08REDNAD_25831         "EGM08_REDNAP_25831.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_GEOIDS_FILE_SPAIN_EGM08REDNAD_CANARIAS_4083         "EGM08_REDNAP_Canarias_4083.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_E2OHC_GEOID_FILE                                  "e2ohc_geoid_file"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_TEMPORAL_PATH       "pp_temporal_path"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASCLIP_FIRST_SHAPEFILE      "pp_lasclip_first_shapefile"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASCLIP_SECOND_SHAPEFILE       "pp_lasclip_second_shapefile"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASCLIP_THIRD_SHAPEFILE       "pp_lasclip_third_shapefile"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASTILE_TILE_SIZE       "pp_lastile_tile_size"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASTILE_TILE_BUFFER       "pp_lastile_tile_buffer"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASGROUND_STEP       "pp_lasground_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASGROUND_CORES       "pp_lasground_cores"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASTILE_CORES       "pp_lastile_cores"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASTHIN_AVT       "pp_lasthin_avt"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASTHIN_AMD       "pp_lasthin_amd"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LAS2DEM_STEP       "pp_las2dem_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LAS2DEM_NODATA       "pp_las2dem_nodata"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LAS2DEM_FILE_SUFFIX       "_dtm.tif"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASTHIN_STEP_OUT_POWERLINE       "pp_lasthin_step_out_powerline"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_OUTPUT_FILE_AUX       "_aux.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_OUTPUT_FILE_AUX2       "_aux2.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_OUTPUT_FILE_REPEATED       "_1.las"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASNOISE_STEP       "pp_lasnoise_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_LASNOISE_ISOLATED       "pp_lasnoise_isolated"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_TEMPORAL_PATH       "sp_temporal_path"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASTILE_TILE_SIZE       "sp_lastile_tile_size"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASTILE_TILE_BUFFER       "sp_lastile_tile_buffer"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASTILE_CORES       "sp_lastile_cores"
//#define POINTCLOUDDB_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASTILE_FLAG_AS_WITHHELD       "sp_lastile_flag_as_withheld"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_FIRST_LASTHIN_STEP       "sp_first_lasthin_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_FIRST_LASTHIN_PERCENTILE       "sp_first_lasthin_percentile"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_FIRST_LASTHIN_CLASSIFY_AS       "sp_first_lasthin_classify_as"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASNOISE_CLASSIFY_AS       "sp_lasnoise_classify_as"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASNOISE_IGNORE_CLASS       "sp_lasnoise_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASNOISE_ISOLATED       "sp_lasnoise_isolated"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASNOISE_STEP_Z       "sp_lasnoise_step_z"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASNOISE_STEP_XY       "sp_lasnoise_step_xy"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_FIRST_LASGROUND_IGNORE_CLASS       "sp_first_lasground_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_FIRST_LASHEIGHT_CLASSIFY_ABOVE       "sp_first_lasheight_classify_above"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_FIRST_LASHEIGHT_CLASSIFY_BELOW       "sp_first_lasheight_classify_below"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASTHIN_STEP       "sp_second_lasthin_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASTHIN_IGNORE_CLASS       "sp_second_lasthin_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASTHIN_CLASSIFY_AS       "sp_second_lasthin_classify_as"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASGROUND_IGNORE_CLASS       "sp_second_lasground_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASGROUND_BULGE       "sp_second_lasground_bulge"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASHEIGHT_CLASSIFICATION       "sp_second_lasheight_classification"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LASHEIGHT_DROP_BELOW       "sp_second_lasheight_drop_below"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_SECOND_LAS2LAS_KEEP_CLASS       "sp_las2las_keep_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_THIRD_LASTHING_IGNORE_CLASS       "sp_third_lasthin_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_THIRD_LASTHING_ADAPTATIVE_VERTICAL_TOLERANCE       "sp_third_lasthin_avt"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_THIRD_LASTHING_ADAPTATIVE_MAXIMUM_DISTANCE       "sp_third_lasthin_amd"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_TEMPORAL_PATH       "gfp_temporal_path"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASTILE_TILE_SIZE       "gfp_lastile_tile_size"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASTILE_TILE_BUFFER       "gfp_lastile_tile_buffer"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASTILE_CORES       "gfp_lastile_cores"
//#define POINTCLOUDDB_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASTILE_FLAG_AS_WITHHELD       "gfp_lastile_flag_as_withheld"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_FIRST_LASTHIN_STEP       "gfp_first_lasthin_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_FIRST_LASTHIN_PERCENTILE       "gfp_first_lasthin_percentile"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_FIRST_LASTHIN_CLASSIFY_AS       "gfp_first_lasthin_classify_as"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASNOISE_CLASSIFY_AS       "gfp_lasnoise_classify_as"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASNOISE_IGNORE_CLASS       "gfp_lasnoise_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASNOISE_ISOLATED       "gfp_lasnoise_isolated"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASNOISE_STEP_Z       "gfp_lasnoise_step_z"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASNOISE_STEP_XY       "gfp_lasnoise_step_xy"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_FIRST_LASGROUND_IGNORE_CLASS       "gfp_first_lasground_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_FIRST_LASHEIGHT_CLASSIFY_ABOVE       "gfp_first_lasheight_classify_above"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_FIRST_LASHEIGHT_CLASSIFY_BELOW       "gfp_first_lasheight_classify_below"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASTHIN_STEP       "gfp_second_lasthin_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASTHIN_IGNORE_CLASS       "gfp_second_lasthin_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASTHIN_CLASSIFY_AS       "gfp_second_lasthin_classify_as"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASGROUND_IGNORE_CLASS       "gfp_second_lasground_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASGROUND_BULGE       "gfp_second_lasground_bulge"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASHEIGHT_CLASSIFICATION       "gfp_second_lasheight_classification"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LASHEIGHT_DROP_BELOW       "gfp_second_lasheight_drop_below"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_SECOND_LAS2LAS_KEEP_CLASS       "gfp_las2las_keep_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_THIRD_LASTHING_IGNORE_CLASS       "gfp_third_lasthin_ignore_class"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_THIRD_LASTHING_ADAPTATIVE_VERTICAL_TOLERANCE       "gfp_third_lasthin_avt"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_THIRD_LASTHING_ADAPTATIVE_MAXIMUM_DISTANCE       "gfp_third_lasthin_amd"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_TEMPORAL_PATH       "bhv_temporal_path"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASTILE_CORES       "bhv_lastile_cores"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASTILE_TILE_SIZE       "bhv_lastile_tile_size"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASTILE_TILE_BUFFER       "bhv_lastile_tile_buffer"
//#define POINTCLOUDDB_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASTILE_FLAG_AS_WITHHELD       "bhv_lastile_flag_as_withheld"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_CORES       "bhv_lasclassify_cores"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_STEP        "bhv_lasclassify_step"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_PLANAR          "bhv_lasclassify_planar"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_RUGED          "bhv_lasclassify_rugged"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_GROUNDOFFSET    "bhv_lasclassify_ground_offset"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_SMALLBUILDINGS    "bhv_lasclassify_small_buildings"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_SMALLTREES    "bhv_lasclassify_small_trees"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_LASCLASSIFY_KEEPOVERHANG    "bhv_lasclassify_keep_overhang"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASBOUNDARY_MERGE    "lbrdy_merge"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_LASBOUNDARY_BOUNDINGBOS    "lbrdy_bb"

// -small_buildings -small_trees -keep_overhang -ground_offset 1.5 -cores 4 -planar 0.20 -step 1.5

//#define POINTCLOUDDB_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_       ""
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_FIRST_CLIP   "firstClip"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_SECOND_CLIP   "secondClip"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_GROUND   "ground"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_FIRST_UNION   "firstUnion"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_SECOND_UNION   "secondUnion"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_TILES   "tiles"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_FIRST_UNION_OUTPUT_FILE_BASENANE   "firstUnion"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_SECOND_UNION_OUTPUT_FILE_BASENANE   "secondUnion"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_LASNOISE   "lasnoise"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_POWERLINE_PREPROCESSING_PATH_LANOISE_OUTPUT_FILE_BASENANE   "lasnoise"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_TILES    "1"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_FIRST_LASTHIN    "2"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_LASNOISE "3"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_FIRST_LASGROUND  "4"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_FIRST_LASHEIGHT  "5"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_SECOND_LASTHIN   "6"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_SECOND_LASGROUND "7"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_SECOND_LASHEIGHT "8"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_LAS2LAS  "ground"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_PATH_LASMERGE "9"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASMERGE_GROUND_FILENAME "ground.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASMERGE_OBJECTS_FILENAME "objects.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_SOLARPARK_PREPROCESSING_LASMERGE_TEMP_FILENAME "temp.laz"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_TILES    "1"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_FIRST_LASTHIN    "2"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_LASNOISE "3"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_FIRST_LASGROUND  "4"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_FIRST_LASHEIGHT  "5"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_SECOND_LASTHIN   "6"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_SECOND_LASGROUND "7"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_SECOND_LASHEIGHT "8"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_LAS2LAS  "ground"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_PATH_LASMERGE "9"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASMERGE_GROUND_FILENAME "ground.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASMERGE_OBJECTS_FILENAME "objects.laz"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_GROUND_FROM_PHOTOGRAMMETRY_LASMERGE_TEMP_FILENAME "temp.laz"

#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_PATH_LASTILES     "1"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_PATH_LASHEIGHT    "2"
#define POINTCLOUDFILE_LASTOOLS_COMMAND_BUILDING_HIGHVEGETATION_PATH_LASCLASSIFY  "3"

#define POINTCLOUDFILE_PROCESS_LIST_FILE                              "/temp.bat"
#define POINTCLOUDFILE_PROCESS_DEFAULT_TEMP_PATH                      "/temp"

#define POINTCLOUDFILE_PROJECT_PARAMETERS_TAG                         "ProjectParameters"

#define POINTCLOUDFILE_NUMBER_OF_POINTS_TO_PROCESS_BY_STEP       100000 // por transactions son 20000, https://www.gdal.org/drv_sqlite.html
#define POINTCLOUDFILE_NUMBER_OF_POINTS_TO_INSERT_BY_SQL_COMMIT       1000000 // por transactions son 20000, https://www.gdal.org/drv_sqlite.html
#define POINTCLOUDFILE_NUMBER_OF_TILES_TO_PROCESS_BY_STEP       1000 // por transactions son 20000, https://www.gdal.org/drv_sqlite.html

#define POINTCLOUDFILE_NUMBER_OF_FILES_TO_WRITE_PROCESS_BY_STEP       1 // por transactions son 20000, https://www.gdal.org/drv_sqlite.html
#define POINTCLOUDFILE_NUMBER_OF_POINTS_TO_WRITE_PROCESS_BY_STEP       100000 // por transactions son 20000, https://www.gdal.org/drv_sqlite.html

#define POINTCLOUDFILE_NO_DOUBLE_VALUE                           -9999
#define POINTCLOUDFILE_NO_DOUBLE_MINIMUM_VALUE                   100000000.
#define POINTCLOUDFILE_DHL_SUFFIX                                "dhl"
#define POINTCLOUDFILE_PCS_SUFFIX                                "pcs"
#define POINTCLOUDFILE_LAS_SUFFIX                                "las"
#define POINTCLOUDFILE_LAZ_SUFFIX                                "laz"
#define POINTCLOUDFILE_OUTPUT_SUBPATH_1                          "libs"
#define POINTCLOUDFILE_OUTPUT_SUBPATH_2                          "pointclouds"
#define POINTCLOUDFILE_HEIGHT_MINIMUM_VALID_VALUE                -200
#define POINTCLOUDFILE_HEIGHT_MAXIMUM_VALID_VALUE                65535/10.+POINTCLOUDFILE_HEIGHT_MINIMUM_VALID_VALUE

#define POINTCLOUDFILE_CLASS_NUMBER_REMOVE                        22 // LAS_1_4_r14.pdf, pag. 30

#define POINTCLOUDFILE_PROJECT_STRING_SEPARATOR                  "#"

#define POINTCLOUDFILE_ROIS_SHAPEFILE_FIELD_ID_NONE              "None"
#define POINTCLOUDFILE_ROIS_SHAPEFILE_FIELD_ID_VALUES_STRING_SEPARATOR     ";"
#define POINTCLOUDFILE_ROI_ID_STRING_SEPARATOR     ";"

#define POINTCLOUDFILE_PROCESS_ROI_UNION_ID                       "ROIUnion"

#define POINTCLOUDFILE_LINEAL_PRECISION                            4
#define POINTCLOUDFILE_GPS_TIME_PRECISION                          6
#define POINTCLOUDFILE_PROCESS_CREATE_POINT_CLOUD_FILE_TAG         "CREATE_PCF"
#define POINTCLOUDFILE_PROCESS_ADD_ROI_TAG                         "ADD_ROI"
#define POINTCLOUDFILE_PROCESS_ADD_POINT_CLOUD_FILE_TAG            "ADD_PCFILE"
#define POINTCLOUDFILE_PROCESS_ADD_POINT_CLOUD_FILES_TAG           "ADD_PCFILES"
#define POINTCLOUDFILE_PROCESS_WRITE_PCFS_TAG                      "WRITE_PCFS"
#define POINTCLOUDFILE_PROCESS_PROCESS_RECLASSIFICATION_CONFUSION_MATRIX_REPORT   "PRCMR"

#define POINTCLOUDFILE_SRID_NO_VALUE                   -1

#define POINTCLOUDFILE_MANAGER_FILE_NAME                   "PointCloudManager.dhl"

#define POINTCLOUDFILE_TILE_PREFIX          "tile_"
#define POINTCLOUDFILE_TILE_STRING_SEPARATOR          "_"

#define POINTCLOUDFILE_ACTION_CHANGE_CLASS "ChangeClass"
#define POINTCLOUDFILE_ACTION_RECOVER_ORIGINAL_CLASS "RecoverOriginalClass"
#define POINTCLOUDFILE_ACTION_DELETE "Delete"
#define POINTCLOUDFILE_ACTION_RECOVER_DELETED "RecoverDeleted"
#define POINTCLOUDFILE_ACTION_ALL_CLASSES_VALUE 255

#define POINTCLOUDFILE_PARAMETER_COLOR      "Color"
#define POINTCLOUDFILE_PARAMETER_GPS_TIME   "GpsTime"
#define POINTCLOUDFILE_PARAMETER_USER_DATA  "UserData"
#define POINTCLOUDFILE_PARAMETER_INTENSITY  "Intensity"
#define POINTCLOUDFILE_PARAMETER_SOURCE_ID  "SourceId"
#define POINTCLOUDFILE_PARAMETER_NIR        "Nir"
#define POINTCLOUDFILE_PARAMETER_RETURN     "Return"
#define POINTCLOUDFILE_PARAMETER_RETURNS    "Returns"
#define POINTCLOUDFILE_PARAMETER_COLOR_BYTES    "ColorBytes"
#define POINTCLOUDFILE_PARAMETER_COLOR_RED      "R"
#define POINTCLOUDFILE_PARAMETER_COLOR_GREEN      "G"
#define POINTCLOUDFILE_PARAMETER_COLOR_BLUE      "B"

#define POINTCLOUDFILE_PYTHON_TAG_POSITION_TILE  "p"
#define POINTCLOUDFILE_PYTHON_TAG_IX             "x"
#define POINTCLOUDFILE_PYTHON_TAG_IY             "y"
#define POINTCLOUDFILE_PYTHON_TAG_Z              "z"
#define POINTCLOUDFILE_PYTHON_TAG_GPS_TIME       "gt"
#define POINTCLOUDFILE_PYTHON_TAG_CLASS          "c"
#define POINTCLOUDFILE_PYTHON_TAG_CLASS_NEW      "cn"
#define POINTCLOUDFILE_PYTHON_TAG_VALUES_8BITS   "v8"
#define POINTCLOUDFILE_PYTHON_TAG_VALUES_16BITS  "v16"

#define POINTCLOUDFILE_TEMPORAL_PROJECT_FILE           "/temp.prj"

/*
#define POINTCLOUDDB_PROCESS_CREATE_DATABASE_TAG                "CREATE_DB"
#define POINTCLOUDDB_PROCESS_ADD_POINTCLOUD_TAG                 "ADD_POINTCLOUD"
#define POINTCLOUDDB_PROCESS_ADD_POINTCLOUD_NEW_TAG             "ADD_POINTCLOUD_NEW" // storePointsData = false
#define POINTCLOUDDB_PROCESS_ADD_ROI_TAG                        "ADD_ROI"
#define POINTCLOUDDB_PROCESS_WRITE_PCFS_TAG                     "WRITE_PCFS"
#define POINTCLOUDDB_PROCESS_PROCESS_RECLASSIFICATION_CONFUSION_MATRIX_REPORT   "PRCMR"

#define POINTCLOUDDB_SPATIALITE_TEMPLATE_DATABASE_FILE          "/PointCloudDb_template.sqlite"
//#define POINTCLOUDDB_SPATIALITE_CREATE_DATABASE_SQL_FILE        "/PointCloudDbTemplates/PointCloudDb_CreateDb.sql"

#define POINTCLOUDDB_SPATIALITE_SRID_TAG                        "#SRID_VALUE#"

#define POINTCLOUDDB_SPATIALITE_TILE_X_Y_TAG                    "#TILE_X_Y#"

#define POINTCLOUDDB_SPATIALITE_SRID_NO_VALUE                   -1

// TABLE: project_parameters
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_TABLE_NAME                 "projects"

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_ID                  "id"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_ID_FIELD_TYPE       SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_REFERENCE_DATE  "1970:01:13"
#define POINTCLOUDDB_SPATIALITE_REFERENCE_DATE_FORMAT "yyyy:MM:dd"

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_LAST_OPEN_TIME                  "id_aux"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_LAST_OPEN_TIME_FIELD_TYPE       SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_CRS_DESCRIPTION                 "crs_description"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_CRS_DESCRIPTION_FIELD_TYPE      SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_CRS_PROJ4_STRING                "crs_proj4_string"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_CRS_PROJ4_STRING_FIELD_TYPE     SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_EPSG_CODE                       "epsg_code"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_EPSG_CODE_FIELD_TYPE            SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_HEIGHT_TYPE                "height_type"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_HEIGHT_TYPE_FIELD_TYPE     SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_GRID_SIZE                       "grid_size"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_GRID_SIZE_FIELD_TYPE            SPATIALITE_FIELD_TYPE_DOUBLE
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_GRID_SIZE_FIELD_PRECISION       3
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_GRID_SIZE_DIFFERENCE_TOLERANCE  0.0001

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_TYPE                "type"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_TYPE_FIELD_TYPE     SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_PARAMETERS                "parameters"
#define POINTCLOUDDB_SPATIALITE_TABLE_PROJECTS_FIELD_PARAMETERS_FIELD_TYPE     SPATIALITE_FIELD_TYPE_TEXT

// TABLE: files
#define POINTCLOUDDB_SPATIALITE_TABLE_FILES_TABLE_NAME                 "files"

#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_ID                 "id"
#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_FILE               "file"
#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_FILE_FIELD_TYPE    SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_USED               "used"
#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_USED_FIELD_TYPE    SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_THE_GEOM                                    "the_geom"
#define POINTCLOUDDB_SPATIALITE_FILES_FIELD_THE_GEOM_FIELD_TYPE                         SPATIALITE_FIELD_TYPE_WKT_GEOMETRY

// TABLE: rois
#define POINTCLOUDDB_SPATIALITE_TABLE_ROIS_TABLE_NAME                 "rois"

#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_ID                 "id"
#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_FILE               "file"
#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_FILE_FIELD_TYPE    SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_ROID_ID               "roi_id"
#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_ROID_ID_FIELD_TYPE    SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_THE_GEOM                                    "the_geom"
#define POINTCLOUDDB_SPATIALITE_ROIS_FIELD_THE_GEOM_FIELD_TYPE                         SPATIALITE_FIELD_TYPE_WKT_GEOMETRY

// TABLE: tiles
#define POINTCLOUDDB_SPATIALITE_TABLE_TILES_TABLE_NAME                 "tiles"

#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_ID                 "id"
#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_TILE_X              "tile_x"
#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_TILE_X_FIELD_TYPE    SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_TILE_Y              "tile_y"
#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_TILE_Y_FIELD_TYPE    SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_TILE                "tile"
#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_TILE_FIELD_TYPE       SPATIALITE_FIELD_TYPE_TEXT

#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_COMPLETED              "completed"
#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_COMPLETED_FIELD_TYPE    SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_THE_GEOM                                    "the_geom"
#define POINTCLOUDDB_SPATIALITE_TILES_FIELD_THE_GEOM_FIELD_TYPE                         SPATIALITE_FIELD_TYPE_WKT_GEOMETRY

// TABLE: tile
//#define POINTCLOUDDB_SPATIALITE_TABLE_TILES_TABLE_NAME                 "tiles"

// No pongo nombres con mas de ocho caracteres por compatibilidad con shapefile
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_ID                 "id"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_FILE_ID                 "file_id"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_FILE_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_FILE_ID_FIELD_TYPE              OFTInteger

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_FILE_POINT_INDEX        "file_pid"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_FILE_POINT_INDEX_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_FILE_POINT_INDEX_FIELD_TYPE      OFTInteger

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_ROI_ID                 "roi_id"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_ROI_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_ROI_ID_FIELD_TYPE               OFTInteger

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_CLASS                 "class"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_CLASS_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_CLASS_FIELD_TYPE            OFTInteger

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_CLASS_NEW                 "class_new"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_CLASS_NEW_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_CLASS_NEW_FIELD_TYPE      OFTInteger

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_ALTITUDE                 "altitude"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_ALTITUDE_FIELD_TYPE      SPATIALITE_FIELD_TYPE_DOUBLE
#define POINTCLOUDDB_OGR_TILE_FIELD_ALTITUDE_FIELD_TYPE      OFTReal

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_HEIGHT                 "height"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_HEIGHT_FIELD_TYPE      SPATIALITE_FIELD_TYPE_DOUBLE
#define POINTCLOUDDB_OGR_TILE_FIELD_HEIGHT_FIELD_TYPE      OFTReal
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_HEIGHT_PARAMETER_CODE   "height"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RETURN                 "return"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RETURN_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_RETURN_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RETURN_PARAMETER_CODE   "return"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RETURNS                 "returns"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RETURNS_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_RETURNS_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RETURNS_PARAMETER_CODE   "returns"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_REMOVE                 "remove"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_REMOVE_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_REMOVE_FIELD_TYPE      OFTInteger

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RED                 "red"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RED_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_RED_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_RED_PARAMETER_CODE   "red"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_GREEN                 "green"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_GREEN_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_GREEN_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_GREEN_PARAMETER_CODE   "green"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_BLUE                 "blue"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_BLUE_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_BLUE_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_BLUE_PARAMETER_CODE   "blue"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_NIR                 "nir"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_NIR_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_NIR_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_NIR_PARAMETER_CODE   "nir"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_INTENSITY                 "intensit"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_INTENSITY_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_INTENSITY_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_INTENSITY_PARAMETER_CODE   "intensity"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_SOURCE_ID                 "src_id"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_SOURCE_ID_FIELD_TYPE      SPATIALITE_FIELD_TYPE_INTEGER
#define POINTCLOUDDB_OGR_TILE_FIELD_SOURCE_ID_FIELD_TYPE      OFTInteger
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_SOURCE_ID_PARAMETER_CODE   "sourceid"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_GPS_TIME                 "gps_time"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_GPS_TIME_FIELD_TYPE      SPATIALITE_FIELD_TYPE_DOUBLE
#define POINTCLOUDDB_OGR_TILE_FIELD_GPS_TIME_FIELD_TYPE      OFTReal
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_GPS_TIMEN_PARAMETER_CODE   "gpstime"

#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_THE_GEOM                                    "the_geom"
#define POINTCLOUDDB_SPATIALITE_TILE_FIELD_THE_GEOM_FIELD_TYPE                         SPATIALITE_FIELD_TYPE_WKT_GEOMETRY

*/
#endif // POINTCLOUDFILEDEFINITIONS_H
